/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SzukajRouteImport } from './routes/szukaj'
import { Route as PokojSlugRouteImport } from './routes/pokoj.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SzukajRoute = SzukajRouteImport.update({
  id: '/szukaj',
  path: '/szukaj',
  getParentRoute: () => rootRouteImport,
} as any)
const PokojSlugRoute = PokojSlugRouteImport.update({
  id: '/pokoj/$slug',
  path: '/pokoj/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/szukaj': typeof SzukajRoute
  '/pokoj/$slug': typeof PokojSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/szukaj': typeof SzukajRoute
  '/pokoj/$slug': typeof PokojSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/szukaj': typeof SzukajRoute
  '/pokoj/$slug': typeof PokojSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/szukaj' | '/pokoj/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/szukaj' | '/pokoj/$slug'
  id: '__root__' | '/' | '/szukaj' | '/pokoj/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SzukajRoute: typeof SzukajRoute
  PokojSlugRoute: typeof PokojSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/szukaj': {
      id: '/szukaj'
      path: '/szukaj'
      fullPath: '/szukaj'
      preLoaderRoute: typeof SzukajRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pokoj/$slug': {
      id: '/pokoj/$slug'
      path: '/pokoj/$slug'
      fullPath: '/pokoj/$slug'
      preLoaderRoute: typeof PokojSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SzukajRoute: SzukajRoute,
  PokojSlugRoute: PokojSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
