/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as SzukajRouteImport } from './routes/szukaj'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedKasaRouteImport } from './routes/_authenticated/kasa'
import { Route as AuthenticatedKontoRouteImport } from './routes/_authenticated/konto'
import { Route as AuthenticatedKoszykRouteImport } from './routes/_authenticated/koszyk'
import { Route as AuthenticatedWystawRouteImport } from './routes/_authenticated/wystaw'
import { Route as PokojSlugRouteImport } from './routes/pokoj.$slug'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const SzukajRoute = SzukajRouteImport.update({
  id: '/szukaj',
  path: '/szukaj',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKasaRoute = AuthenticatedKasaRouteImport.update({
  id: '/kasa',
  path: '/kasa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKontoRoute = AuthenticatedKontoRouteImport.update({
  id: '/konto',
  path: '/konto',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKoszykRoute = AuthenticatedKoszykRouteImport.update({
  id: '/koszyk',
  path: '/koszyk',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWystawRoute = AuthenticatedWystawRouteImport.update({
  id: '/wystaw',
  path: '/wystaw',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PokojSlugRoute = PokojSlugRouteImport.update({
  id: '/pokoj/$slug',
  path: '/pokoj/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/szukaj': typeof SzukajRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/kasa': typeof AuthenticatedKasaRoute
  '/konto': typeof AuthenticatedKontoRoute
  '/koszyk': typeof AuthenticatedKoszykRoute
  '/wystaw': typeof AuthenticatedWystawRoute
  '/pokoj/$slug': typeof PokojSlugRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/szukaj': typeof SzukajRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/kasa': typeof AuthenticatedKasaRoute
  '/konto': typeof AuthenticatedKontoRoute
  '/koszyk': typeof AuthenticatedKoszykRoute
  '/wystaw': typeof AuthenticatedWystawRoute
  '/pokoj/$slug': typeof PokojSlugRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/szukaj': typeof SzukajRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/kasa': typeof AuthenticatedKasaRoute
  '/_authenticated/konto': typeof AuthenticatedKontoRoute
  '/_authenticated/koszyk': typeof AuthenticatedKoszykRoute
  '/_authenticated/wystaw': typeof AuthenticatedWystawRoute
  '/pokoj/$slug': typeof PokojSlugRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/szukaj'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/kasa'
    | '/konto'
    | '/koszyk'
    | '/wystaw'
    | '/pokoj/$slug'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/szukaj'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/kasa'
    | '/konto'
    | '/koszyk'
    | '/wystaw'
    | '/pokoj/$slug'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/szukaj'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/admin'
    | '/_authenticated/kasa'
    | '/_authenticated/konto'
    | '/_authenticated/koszyk'
    | '/_authenticated/wystaw'
    | '/pokoj/$slug'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  SzukajRoute: typeof SzukajRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  PokojSlugRoute: typeof PokojSlugRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/szukaj': {
      id: '/szukaj'
      path: '/szukaj'
      fullPath: '/szukaj'
      preLoaderRoute: typeof SzukajRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kasa': {
      id: '/_authenticated/kasa'
      path: '/kasa'
      fullPath: '/kasa'
      preLoaderRoute: typeof AuthenticatedKasaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/konto': {
      id: '/_authenticated/konto'
      path: '/konto'
      fullPath: '/konto'
      preLoaderRoute: typeof AuthenticatedKontoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/koszyk': {
      id: '/_authenticated/koszyk'
      path: '/koszyk'
      fullPath: '/koszyk'
      preLoaderRoute: typeof AuthenticatedKoszykRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wystaw': {
      id: '/_authenticated/wystaw'
      path: '/wystaw'
      fullPath: '/wystaw'
      preLoaderRoute: typeof AuthenticatedWystawRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/pokoj/$slug': {
      id: '/pokoj/$slug'
      path: '/pokoj/$slug'
      fullPath: '/pokoj/$slug'
      preLoaderRoute: typeof PokojSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedKasaRoute: typeof AuthenticatedKasaRoute
  AuthenticatedKontoRoute: typeof AuthenticatedKontoRoute
  AuthenticatedKoszykRoute: typeof AuthenticatedKoszykRoute
  AuthenticatedWystawRoute: typeof AuthenticatedWystawRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedKasaRoute: AuthenticatedKasaRoute,
  AuthenticatedKontoRoute: AuthenticatedKontoRoute,
  AuthenticatedKoszykRoute: AuthenticatedKoszykRoute,
  AuthenticatedWystawRoute: AuthenticatedWystawRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  SzukajRoute: SzukajRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  PokojSlugRoute: PokojSlugRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
